### ISSUE TITLE
SOLVED: AceJump 3.0.2 gives NullPointerException in PyCharm Pro 2016.2 on Ubuntu 16.04 at every invocation

### ISSUE THREAD

**Issue by cpbotha** [johnlindquist/AceJump#100]
As I was logging this issue, the problem went away when I eventually reset and re-set my custom AceJump keybinding. I'm still submitting this so that anyone else with the same problem can solve it quickly. Please close the issue as soon as you see it! :)

I was planning to make a short screencast with AceJump tonight, because I was really happy with the improvements you'd implemented with 3.0. (3.0.0 definitely worked, and 3.0.1 also)

However, PyCharm wanted me to update 3.0.2, so I did and restarted PyCharm. From then on, whenever I press my AceJump shortcut key, I get the KotlinNullpointerException below.

As you can see in the attached screenshot, it does draw the block it usually does when I invoke it, but then the exception is raised, and I get no further.

This issue went away when I reset my non-standard keybinding (`C-c j` same as I have in Emacs with Avy Jump) to the default. After this I could even reconfigure my preferred custom keybinding, and all was well.

```
null
kotlin.KotlinNullPointerException
	at com.johnlindquist.acejump.ui.SearchBox.<init>(SearchBox.kt:81)
	at com.johnlindquist.acejump.AceJumpAction.actionPerformed(AceJumpAction.kt:33)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:356)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.c(IdeKeyEventDispatcher.java:292)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:217)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:607)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

![image](https://cloud.githubusercontent.com/assets/937871/19982099/57b6e6d2-a20d-11e6-85ee-0159d1dc551d.png)

**Comment by cpbotha** [comment]
Here's that screencast in case anyone is interested: https://youtu.be/8cgy8ITtsJE
