### ISSUE TITLE
AceJump threw an uncaught NoSuchFieldError

### ISSUE THREAD

**Issue by amandle** [johnlindquist/AceJump#113]
Triggering AceJump (Ctrl + ;) causes an error message "AceJump threw an uncaught NoSuchFieldError" 

AceJump 3.1.1

`ACTIONS_KEY
java.lang.NoSuchFieldError: ACTIONS_KEY
	at com.johnlindquist.acejump.KeyboardHandler.resetUIState(KeyboardHandler.kt:124)
	at com.johnlindquist.acejump.ui.AceUI.setEditor(AceUI.kt:26)
	at com.johnlindquist.acejump.AceAction.actionPerformed(AceAction.kt:19)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by TheKhaeng** [comment]
![screen shot 2559-12-11 at 00 26 05](https://cloud.githubusercontent.com/assets/13915498/21074935/70319df4-bf38-11e6-8377-a6822b2482e3.png)

**Comment by grepx** [comment]
If it's of any help, this is happening for me on the latest version of android studio and AceJump AceJump 3.1.1.

Android Studio 2.2.3
Build #AI-145.3537739, built on December 2, 2016
JRE: 1.8.0_112-release-b05 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by grepx** [comment]
I decided to work around this by cloning the repo and building an older version. I randomly picked commit a92c866 (version 3.0.4) and that seems to work fine. Probably newer versions also work if someone wants to investigate further. I've attached the build.
[AceJump-3.0.4.zip](https://github.com/johnlindquist/AceJump/files/651353/AceJump-3.0.4.zip)

**Comment by TheKhaeng** [comment]
version 3.0.7 work fine to Android Studio 2.2.3
link to download this version 
https://plugins.jetbrains.com/plugin/7086

and install manual :)
<img width="294" alt="screen shot 2559-12-14 at 18 58 14" src="https://cloud.githubusercontent.com/assets/13915498/21181192/506ac032-c22f-11e6-90bb-a4bdda89d203.png">
