### ISSUE TITLE
A caret

### ISSUE THREAD

**Issue by sergeychibunin** [johnlindquist/AceJump#122]
Unexpected caret move request
java.lang.Throwable
	at com.intellij.diagnostic.LogMessageEx.error(LogMessageEx.java:116)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToLogicalPosition(CaretImpl.java:707)
	at com.intellij.openapi.editor.impl.CaretImpl.a(CaretImpl.java:214)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:439)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToOffset(CaretImpl.java:212)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToOffset(CaretImpl.java:202)
	at com.intellij.openapi.editor.impl.EditorImpl.reinitSettings(EditorImpl.java:882)
	at com.intellij.openapi.editor.impl.SettingsImpl.a(SettingsImpl.java:667)
	at com.intellij.openapi.editor.impl.SettingsImpl.setBlinkCaret(SettingsImpl.java:534)
	at com.johnlindquist.acejump.ui.AceUI.restoreEditorSettings(AceUI.kt:99)
	at com.johnlindquist.acejump.KeyboardHandler.resetUIState(KeyboardHandler.kt:157)
	at com.johnlindquist.acejump.KeyboardHandler.reset(KeyboardHandler.kt:136)
	at com.johnlindquist.acejump.KeyboardHandler$resetIfCaretPositionChanged$1.caretPositionChanged(KeyboardHandler.kt:71)
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy27.caretPositionChanged(Unknown Source)
	at com.intellij.openapi.editor.impl.CaretModelImpl.fireCaretPositionChanged(CaretModelImpl.java:524)
	at com.intellij.openapi.editor.impl.CaretImpl.a(CaretImpl.java:588)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToLogicalPosition(CaretImpl.java:715)
	at com.intellij.openapi.editor.impl.CaretImpl.a(CaretImpl.java:431)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:439)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToLogicalPosition(CaretImpl.java:431)
	at com.intellij.openapi.editor.impl.CaretModelImpl.a(CaretModelImpl.java:487)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:444)
	at com.intellij.openapi.editor.impl.CaretModelImpl.setCaretsAndSelections(CaretModelImpl.java:464)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorProvider.setStateImpl(TextEditorProvider.java:281)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.setStateImpl(PsiAwareTextEditorProvider.java:114)
	at com.intellij.openapi.fileEditor.impl.text.AsyncEditorLoader.setEditorState(AsyncEditorLoader.java:209)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.setState(TextEditorImpl.java:122)
	at com.intellij.openapi.fileEditor.impl.IdeDocumentHistoryImpl.d(IdeDocumentHistoryImpl.java:459)
	at com.intellij.openapi.fileEditor.impl.IdeDocumentHistoryImpl.e(IdeDocumentHistoryImpl.java:394)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.fileEditor.impl.IdeDocumentHistoryImpl.executeCommand(IdeDocumentHistoryImpl.java:564)
	at com.intellij.openapi.fileEditor.impl.IdeDocumentHistoryImpl.navigatePreviousChange(IdeDocumentHistoryImpl.java:394)
	at com.intellij.ide.actions.JumpToLastEditAction.actionPerformed(JumpToLastEditAction.java:27)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.b(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by breandan** [comment]
Duplicates #121, thanks for reporting.

**Comment by indkumar8999** [comment]
Someone Please find a solution asap for this, I am also getting the same problem

**Comment by breandan** [comment]
Does it occur every time you use AceJump?
