### ISSUE TITLE
Could not initialize class com.johnlindquist.acejump.ui.AceUI

### ISSUE THREAD

**Issue by realEudemonia** [johnlindquist/AceJump#126]
Doesn't work right out of the box and I'm not the most tech savvy individual. Just learning to code. 

**OS**: Linux Mint 17.3 Cinnamon 64-bit

**IDE**: WebStorm 2016.3.3

**Keymap**: Reset to Default

**Other plugins**: Tried disabling Key Promoter in case of a conflict, but didn't work. The only other 3rd party plugin I have is Material Theme UI. 

**Error log**:
Could not initialize class com.johnlindquist.acejump.ui.AceUI
java.lang.NoClassDefFoundError: Could not initialize class com.johnlindquist.acejump.ui.AceUI
	at com.johnlindquist.acejump.AceAction.actionPerformed(AceAction.kt:17)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.f(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by breandan** [comment]
Please follow #130 for updates. Thank you for reporting!
