### ISSUE TITLE
Could not initialize class com.johnlindquist.acejump.KeyboardHandler

### ISSUE THREAD

**Issue by hahaha1w** [johnlindquist/AceJump#127]
error stack 
`kotlin/collections/MapsKt
java.lang.NoClassDefFoundError: kotlin/collections/MapsKt
	at com.johnlindquist.acejump.KeyboardHandler.<init>(KeyboardHandler.kt:38)
	at com.johnlindquist.acejump.KeyboardHandler.<clinit>(KeyboardHandler.kt:31)
	at com.johnlindquist.acejump.ui.AceUI.setEditor(AceUI.kt:53)
	at com.johnlindquist.acejump.AceAction.actionPerformed(AceAction.kt:17)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.c(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: kotlin.collections.MapsKt PluginClassLoader[AceJump, 3.2.0]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
`

**Comment by breandan** [comment]
This is caused by an older version of Kotlin, probably running on an older IDE version. I am hesitant to bundle a fixed version of Kotlin with the plugin, but there are [several issues](https://github.com/johnlindquist/AceJump/issues?utf8=%E2%9C%93&q=NoClassDefFoundError) like this one.

**Comment by breandan** [comment]
This issue should no longer affect AceJump users. If you encounter this error on recent versions of AceJump, please feel free to re-open this ticket.
