### ISSUE TITLE
Ctrl + ; error on mac

### ISSUE THREAD

**Issue by zhuweiyou** [johnlindquist/AceJump#129]
WebStorm 2016.3.4

```
java.lang.ExceptionInInitializerError
	at com.johnlindquist.acejump.AceAction.actionPerformed(AceAction.kt:17)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: kotlin.KotlinNullPointerException
	at com.johnlindquist.acejump.search.AceUtilKt.getDefaultEditor(AceUtil.kt:11)
	at com.johnlindquist.acejump.ui.AceUI.<init>(AceUI.kt:21)
	at com.johnlindquist.acejump.ui.AceUI.<clinit>(AceUI.kt:15)
	... 17 more
```

**Comment by gabid-asos** [comment]
I'm having the same issue. Same stacktrace as reported by zhuweiyou. Also using the plugin with WebStorm 2016.3.4 on OS X 10.11.

**Comment by zreisman** [comment]
Same.

**Comment by Fred-J** [comment]
Same problem here with:
MacBook Pro, El Capitan, Webstorm 11.0.4 and Ace Jump 3.2.0
When I type Ctrl+; and any letter, it fails to activate the mode and actually types the letter instead of searching for it.
Any idea how to fix it?
