### ISSUE TITLE
Assertion failed exception

### ISSUE THREAD

**Issue by psafarov** [johnlindquist/AceJump#138]
After pressing Ctrl+; the following exception is thrown, also acejump and ideavim stop working correctly.

```
Assertion failed
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:177)
	at com.intellij.openapi.editor.impl.ScrollingModelImpl.removeVisibleAreaListener(ScrollingModelImpl.java:401)
	at com.johnlindquist.acejump.KeyboardHandler.removeListeners(KeyboardHandler.kt:229)
	at com.johnlindquist.acejump.KeyboardHandler.reset(KeyboardHandler.kt:208)
	at com.johnlindquist.acejump.ui.AceUI.setEditor(AceUI.kt:36)
	at com.johnlindquist.acejump.KeyboardHandler.configureEditor(KeyboardHandler.kt:144)
	at com.johnlindquist.acejump.KeyboardHandler.access$configureEditor(KeyboardHandler.kt:36)
	at com.johnlindquist.acejump.KeyboardHandler$startListening$1.invoke(KeyboardHandler.kt:169)
	at com.johnlindquist.acejump.KeyboardHandler.startListening(KeyboardHandler.kt:174)
	at com.johnlindquist.acejump.KeyboardHandler.access$startListening(KeyboardHandler.kt:36)
	at com.johnlindquist.acejump.KeyboardHandler$activate$1.run(KeyboardHandler.kt:65)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:672)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:685)
	at com.johnlindquist.acejump.KeyboardHandler.activate(KeyboardHandler.kt:64)
	at com.johnlindquist.acejump.AceAction.actionPerformed(AceAction.kt:17)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:570)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:619)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:618)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.f(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:633)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by doneel** [comment]
I can reproduce this every time I trigger the ```AceAction``` function through a keybind.

IdeaVim 0.48

AceJump 3.2.2

```
IntelliJ IDEA 2017.1.3
Build #IC-171.4424.56, built on May 12, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4
```

**Comment by vincentjames501** [comment]
+1

**Comment by vincentjames501** [comment]
This is huge for me. After I get this exception I can't type into the editor anymore!

**Comment by msafi** [comment]
Same here. Odd thing is that I get this error in most projects but there's one in particular where I don't get this error. Not sure why. So there's probably a workaround to this problem. If anyone know what it is, please share!

**Comment by breandan** [comment]
Another user reports this occurs when multiple IDE windows are open. Can anyone else corroborate? https://github.com/johnlindquist/AceJump/issues/140#issuecomment-304894924 @ZizhangAi

**Comment by doneel** [comment]
@breandan I can confirm that this only happens when I have multiple IntelliJ windows open. Good catch!

**Comment by vincentjames501** [comment]
+1

**Comment by msafi** [comment]
Sometimes I have multiple IntelliJ windows open and I don't get this issue.

**Comment by breandan** [comment]
The error is not guaranteed to happen if you have multiple windows open, but if the wrong editor is selected AceJump will crash. Investigating, I should have a fix shortly.

**Comment by rogueleaderr** [comment]
Thanks for looking into it @breandan! Not having AceJump work makes me realize how much I miss it when I can't use it! :)

**Comment by breandan** [comment]
This bug should now be fixed in the [latest update](https://plugins.jetbrains.com/plugin/7086-acejump/update/35584). Please feel free to reopen if the issue persists. Thanks to @psafarov @doneel @SvitlanaShepitsena for reporting and @ZizhangAi for helping identify the cause.
