### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by startwang** [johnlindquist/AceJump#140]
Assertion failed
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:168)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:177)
	at com.intellij.openapi.editor.impl.ScrollingModelImpl.removeVisibleAreaListener(ScrollingModelImpl.java:401)
	at com.johnlindquist.acejump.KeyboardHandler.removeListeners(KeyboardHandler.kt:229)
	at com.johnlindquist.acejump.KeyboardHandler.reset(KeyboardHandler.kt:208)
	at com.johnlindquist.acejump.ui.AceUI.setEditor(AceUI.kt:36)
	at com.johnlindquist.acejump.KeyboardHandler.configureEditor(KeyboardHandler.kt:144)
	at com.johnlindquist.acejump.KeyboardHandler.access$configureEditor(KeyboardHandler.kt:36)
	at com.johnlindquist.acejump.KeyboardHandler$startListening$1.invoke(KeyboardHandler.kt:169)
	at com.johnlindquist.acejump.KeyboardHandler.startListening(KeyboardHandler.kt:174)
	at com.johnlindquist.acejump.KeyboardHandler.access$startListening(KeyboardHandler.kt:36)
	at com.johnlindquist.acejump.KeyboardHandler$activate$1.run(KeyboardHandler.kt:65)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:672)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:685)
	at com.johnlindquist.acejump.KeyboardHandler.activate(KeyboardHandler.kt:64)
	at com.johnlindquist.acejump.AceAction.actionPerformed(AceAction.kt:17)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:570)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:619)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:618)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:633)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ZizhangAi** [comment]
I encounter this problem when I have multiple webstorm windows open on my mac: when I use the hot key to initiate it the focus is not on the current screen, and an exception is thrown.

**Comment by breandan** [comment]
Been puzzled by this issue for a while. Realized I was trying to reproduce with one window. If the editor targeted was not the original editor, it would cause this error. @ZizhangAi This was helpful, thanks!

**Comment by breandan** [comment]
This error should now be fixed in the [latest update](https://plugins.jetbrains.com/plugin/7086-acejump/update/35584. Please feel free to reopen #138 if the issue persists. Thanks for reporting!
