### ISSUE TITLE
NoSuchMethodError on initialiazing search

### ISSUE THREAD

**Issue by athkalia** [johnlindquist/AceJump#160]
Hello,

Plugin used to work okay, but a few weeks ago it stopped working. Getting the following exception on Android Studio, as soon as I initiate a search:

```kotlin.jvm.internal.FunctionReference.<init>(ILjava/lang/Object;)V
java.lang.NoSuchMethodError: kotlin.jvm.internal.FunctionReference.<init>(ILjava/lang/Object;)V
	at com.johnlindquist.acejump.KeyboardHandler$uninstallCustomShortCutHandler$1$1.<init>(KeyboardHandler.kt)
	at com.johnlindquist.acejump.KeyboardHandler.uninstallCustomShortCutHandler(KeyboardHandler.kt:165)
	at com.johnlindquist.acejump.KeyboardHandler.access$uninstallCustomShortCutHandler(KeyboardHandler.kt:35)
	at com.johnlindquist.acejump.KeyboardHandler$reset$1.invoke(KeyboardHandler.kt:200)
	at com.johnlindquist.acejump.KeyboardHandler.reset(KeyboardHandler.kt:207)
	at com.johnlindquist.acejump.KeyboardHandler$keyMap$6.invoke(KeyboardHandler.kt:47)
	at com.johnlindquist.acejump.KeyboardHandler$keyMap$6.invoke(KeyboardHandler.kt:35)
	at com.johnlindquist.acejump.KeyboardHandler.processCommand(KeyboardHandler.kt:72)
	at com.johnlindquist.acejump.AceKeyAction.actionPerformed(AceAction.kt:42)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:609)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Then Android Studio completely freaks out as I stay in search mode, escape doesn't work, typing doesn't work etc. I am on Windows, Android Studio 

Android Studio 2.3.3
Build #AI-162.4069837, built on June 6, 2017
JRE: 1.8.0_112-release-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Latest version of the plugin : 3.2.7

Thanks in advance

**Comment by breandan** [comment]
Should be fixed. Please feel to reopen if issue persists after updating to AceJump 3.3.0+, thanks for reporting!

**Comment by athkalia** [comment]
yup, fixed. Thanks pal!
