### ISSUE TITLE
Unexpected caret move request

### ISSUE THREAD

**Issue by a5530181** [johnlindquist/AceJump#169]
Unexpected caret move request
java.lang.Throwable
	at com.intellij.diagnostic.LogMessageEx.error(LogMessageEx.java:116)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToLogicalPosition(CaretImpl.java:707)
	at com.intellij.openapi.editor.impl.CaretImpl.a(CaretImpl.java:214)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:439)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToOffset(CaretImpl.java:212)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToOffset(CaretImpl.java:202)
	at com.intellij.openapi.editor.impl.EditorImpl.reinitSettings(EditorImpl.java:882)
	at com.intellij.openapi.editor.impl.SettingsImpl.b(SettingsImpl.java:667)
	at com.intellij.openapi.editor.impl.SettingsImpl.setBlinkCaret(SettingsImpl.java:534)
	at com.johnlindquist.acejump.ui.AceUI$restoreCursor$1.run(AceUI.kt:103)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:650)
	at com.johnlindquist.acejump.ui.AceUI.restoreCursor(AceUI.kt:101)
	at com.johnlindquist.acejump.ui.AceUI.restoreEditorSettings(AceUI.kt:90)
	at com.johnlindquist.acejump.KeyboardHandler.reset(KeyboardHandler.kt:204)
	at com.johnlindquist.acejump.KeyboardHandler.reset$default(KeyboardHandler.kt:198)
	at com.johnlindquist.acejump.KeyboardHandler$resetListener$1.caretPositionChanged(KeyboardHandler.kt:135)
	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy29.caretPositionChanged(Unknown Source)
	at com.intellij.openapi.editor.impl.CaretModelImpl.fireCaretPositionChanged(CaretModelImpl.java:524)
	at com.intellij.openapi.editor.impl.CaretImpl.a(CaretImpl.java:588)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToLogicalPosition(CaretImpl.java:715)
	at com.intellij.openapi.editor.impl.CaretImpl.afterDocumentChange(CaretImpl.java:866)
	at com.intellij.openapi.editor.impl.CaretModelImpl.a(CaretModelImpl.java:87)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:444)
	at com.intellij.openapi.editor.impl.CaretModelImpl.documentChanged(CaretModelImpl.java:85)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:791)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:727)
	at com.intellij.openapi.editor.impl.DocumentImpl.deleteString(DocumentImpl.java:510)
	at com.intellij.openapi.command.impl.EditorChangeAction.a(EditorChangeAction.java:101)
	at com.intellij.openapi.command.impl.EditorChangeAction.performUndo(EditorChangeAction.java:78)
	at com.intellij.openapi.command.impl.EditorChangeAction.undo(EditorChangeAction.java:65)
	at com.intellij.openapi.command.impl.UndoableGroup.a(UndoableGroup.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:934)
	at com.intellij.openapi.command.impl.UndoableGroup.c(UndoableGroup.java:124)
	at com.intellij.openapi.command.impl.UndoableGroup.a(UndoableGroup.java:112)
	at com.intellij.openapi.command.impl.UndoableGroup.undo(UndoableGroup.java:94)
	at com.intellij.openapi.command.impl.Undo.performAction(Undo.java:46)
	at com.intellij.openapi.command.impl.UndoRedo.execute(UndoRedo.java:143)
	at com.intellij.openapi.command.impl.CommandMerger.undoOrRedo(CommandMerger.java:217)
	at com.intellij.openapi.command.impl.UndoManagerImpl.a(UndoManagerImpl.java:412)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.UndoManagerImpl.a(UndoManagerImpl.java:424)
	at com.intellij.openapi.command.impl.UndoManagerImpl.undo(UndoManagerImpl.java:392)
	at com.intellij.ide.actions.UndoAction.perform(UndoAction.java:30)
	at com.intellij.ide.actions.UndoRedoAction.actionPerformed(UndoRedoAction.java:39)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.e(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by a5530181** [comment]
macos IJ idea

**Comment by breandan** [comment]
Duplicates #132. Please report there if you have any further information. Thanks!
