### ISSUE TITLE
Line must not be negative error

### ISSUE THREAD

**Issue by breandan** [johnlindquist/AceJump#174]
```
line must be non negative: -1
java.lang.IllegalArgumentException: line must be non negative: -1
	at com.intellij.openapi.editor.VisualPosition.<init>(VisualPosition.java:52)
	at com.intellij.openapi.editor.VisualPosition.<init>(VisualPosition.java:48)
	at com.johnlindquist.acejump.search.AceUtilKt.visualLineToLogicalLine(AceUtil.kt:161)
	at com.johnlindquist.acejump.search.AceUtilKt.getView(AceUtil.kt:74)
	at com.johnlindquist.acejump.control.Handler.restoreScroll(Handler.kt:233)
	at com.johnlindquist.acejump.control.Handler.restoreSettings(Handler.kt:227)
	at com.johnlindquist.acejump.control.Handler.reset(Handler.kt:196)
	at com.johnlindquist.acejump.view.Model.setEditor(Model.kt:31)
	at com.johnlindquist.acejump.control.AceAction.actionPerformed(AceAction.kt:16)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:624)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.f(IdeKeyEventDispatcher.java:479)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:621)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by breandan** [comment]
Closing due to inactivity (should be fixed). Feel free to reopen if you reencounter this one.
