### ISSUE TITLE
AceJump threw an uncaught NoSuchMethodError. 

### ISSUE THREAD

**Issue by MinRam** [johnlindquist/AceJump#195]
it throw a error when i press the shortcut(crtl+;) .what's more , i had to retart my IDE(Android Studio 2.3.3) if i would like to continue use the AceJump(3.4.0). 

> NoSuchMethodError: com.intellij.openapi.editor.ScrollingModel.scroll(II)V

```java
com.intellij.openapi.editor.ScrollingModel.scroll(II)V
java.lang.NoSuchMethodError: com.intellij.openapi.editor.ScrollingModel.scroll(II)V
	at com.johnlindquist.acejump.control.Handler.restoreScroll(Handler.kt:234)
	at com.johnlindquist.acejump.control.Handler.restoreSettings(Handler.kt:227)
	at com.johnlindquist.acejump.control.Handler.reset(Handler.kt:196)
	at com.johnlindquist.acejump.view.Model.setEditor(Model.kt:31)
	at com.johnlindquist.acejump.control.AceAction.actionPerformed(AceAction.kt:16)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:609)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by breandan** [comment]
Duplicates #182. This should be fixed in the latest release. Please report back if you encounter the error again. Thanks!
