### ISSUE TITLE
java.lang.NoSuchMethodError: kotlin.jvm.internal.FunctionReference.<init>(ILjava/lang/Object;)V

### ISSUE THREAD

**Issue by MinRam** [johnlindquist/AceJump#200]
It throws a error when i start to use AceJump,and I alse see the same error from #160 , #149  , #143 ,
Does it throws error due to my some wrong operatrions?

the Information of IDE below:
- AceJump 3.4.2 
- Android Studio 2.3.3
- Build #AI-162.4069837, built on June 6, 2017
- JRE: 1.8.0_112-release-b06 amd64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
 
>
``` java 
kotlin.jvm.internal.FunctionReference.<init>(ILjava/lang/Object;)V
java.lang.NoSuchMethodError: kotlin.jvm.internal.FunctionReference.<init>(ILjava/lang/Object;)V
	at com.johnlindquist.acejump.view.Canvas$storeBounds$1.<init>(Canvas.kt)
	at com.johnlindquist.acejump.view.Canvas.storeBounds(Canvas.kt:44)
	at com.johnlindquist.acejump.view.Canvas.bindCanvas(Canvas.kt:32)
	at com.johnlindquist.acejump.control.Handler.configureEditor(Handler.kt:76)
	at com.johnlindquist.acejump.control.Handler.start(Handler.kt:108)
	at com.johnlindquist.acejump.control.Handler.access$start(Handler.kt:32)
	at com.johnlindquist.acejump.control.Handler$activate$1.invoke(Handler.kt:52)
	at com.johnlindquist.acejump.control.Handler$activate$1.invoke(Handler.kt:32)
	at com.johnlindquist.acejump.search.AceUtilKt$sam$Runnable$b83511ca.run(AceUtil.kt)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:626)
	at com.johnlindquist.acejump.search.AceUtilKt.runAndWait(AceUtil.kt:28)
	at com.johnlindquist.acejump.control.Handler.activate(Handler.kt:52)
	at com.johnlindquist.acejump.control.AceAction.actionPerformed(AceAction.kt:26)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:609)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Thanks for debug~

**Comment by andrewvmail** [comment]
am also getting this on phpstorm 10, updated to 2018 and its fine ...

**Comment by breandan** [comment]
This error is caused by the following line: 

https://github.com/acejump/AceJump/blob/6ca3ec3d6bec852c4dc026031fa820e785481c8f/src/main/kotlin/org/acejump/view/Canvas.kt#L47

Older platform versions do not support the method reference syntax (introduced in JDK 1.8). The Kotlin compiler really should handle this by translating `::` to Java 7 compatible bytecode when targteting older versions. Or maybe it does and we're not targeting the right bytecode version in the buildscript... :frowning_face:

**Comment by breandan** [comment]
This issue is caused by an outdated version of the Kotlin runtime bundled with older platform versions. Will bump the minimum required version, recommend updating to at least a `2018.2` release or greater in order to run recent versions of AceJump.
