### ISSUE TITLE
Plugin error: IntelliJ IDEA 2016.3.4

### ISSUE THREAD

**Issue by stokilo** [johnlindquist/AceJump#212]
IntelliJ IDEA 2016.3.4
Build #IU-163.12024.16, built on January 31, 2017
JRE: 1.8.0_112-release-408-b6 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

+ IdeaVim plugin installed, following exception occured:

```
kotlin.jvm.internal.FunctionReference.<init>(ILjava/lang/Object;)V
java.lang.NoSuchMethodError: kotlin.jvm.internal.FunctionReference.<init>(ILjava/lang/Object;)V
	at com.johnlindquist.acejump.view.Canvas$storeBounds$1.<init>(Canvas.kt)
	at com.johnlindquist.acejump.view.Canvas.storeBounds(Canvas.kt:44)
	at com.johnlindquist.acejump.view.Canvas.bindCanvas(Canvas.kt:32)
	at com.johnlindquist.acejump.control.Handler.configureEditor(Handler.kt:76)
	at com.johnlindquist.acejump.control.Handler.start(Handler.kt:108)
	at com.johnlindquist.acejump.control.Handler.access$start(Handler.kt:32)
	at com.johnlindquist.acejump.control.Handler$activate$1.invoke(Handler.kt:52)
	at com.johnlindquist.acejump.control.Handler$activate$1.invoke(Handler.kt:32)
	at com.johnlindquist.acejump.search.AceUtilKt$sam$Runnable$b83511ca.run(AceUtil.kt)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:650)
	at com.johnlindquist.acejump.search.AceUtilKt.runAndWait(AceUtil.kt:28)
	at com.johnlindquist.acejump.control.Handler.activate(Handler.kt:52)
	at com.johnlindquist.acejump.control.AceAction.actionPerformed(AceAction.kt:26)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:215)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.e(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by stokilo** [comment]
Duplicate of: https://github.com/johnlindquist/AceJump/issues/200
