### ISSUE TITLE
Exception with AceJump and WebStorm 5.0 RC (121.150) on Mac

### ISSUE THREAD

**Issue by topka** [johnlindquist/AceJump#3]
I hit Cmd+; and get this exception. Nothing seems to work.

Error during dispatching of java.awt.event.KeyEvent[KEY_PRESSED,keyCode=59,keyText=;,keyChar=';',modifiers=⌘,extModifiers=⌘,keyLocation=KEY_LOCATION_STANDARD,rawCode=0,primaryLevelUnicode=0,scancode=0] on frame2
java.lang.NullPointerException
	at com.johnlindquist.acejump.AceJumpAction.actionPerformed(AceJumpAction.java:76)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:560)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:608)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:208)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:421)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:379)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by breandan** [comment]
The default keystroke is <kbd>ctrl</kbd>+<kbd>;</kbd> on the Mac. Unsure if this is still an issue, since the plugin was recently rewritten. Let me know if you have an issue with the latest beta and I will reopen. Thanks!

https://github.com/johnlindquist/AceJump/releases/tag/3.0.0
