### ISSUE TITLE
NPI on invoking AceJump in latest RubyMine

### ISSUE THREAD

**Issue by develop7** [johnlindquist/AceJump#4]
Environment: RubyMine 4.5.3

Here's exception trace:
```
Error during dispatching of java.awt.event.KeyEvent[KEY_PRESSED,keyCode=59,keyText=Semicolon,keyChar=';',modifiers=Ctrl,extModifiers=Ctrl,keyLocation=KEY_LOCATION_STANDARD,rawCode=47,primaryLevelUnicode=59,scancode=0,extendedKeyCode=0x3b] on frame0
java.lang.NullPointerException
	at com.johnlindquist.acejump.AceJumpAction.actionPerformed(AceJumpAction.java:76)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:545)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:593)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:461)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:525)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:421)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:379)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:151)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:147)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:139)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)

```

**Comment by breandan** [comment]
Closing due to complete rewrite. Please update to the latest version and let me know if this persists. Thanks!
