### ISSUE TITLE
IntelliJ 2016.1 : NoClassDefFoundError

### ISSUE THREAD

**Issue by SimenB** [johnlindquist/AceJump#61]
On invocation of shortcut

```
2016-03-18 11:10:15,727 [4648624]  ERROR - llij.ide.plugins.PluginManager - com/johnlindquist/acejump/AceFinder 
java.lang.NoClassDefFoundError: com/johnlindquist/acejump/AceFinder
	at com.johnlindquist.acejump.AceJumpAction.actionPerformed(AceJumpAction.kt:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.e(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:631)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2016-03-18 11:10:15,728 [4648625]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2016.1  Build #IU-145.257.12 
2016-03-18 11:10:15,728 [4648625]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_76-release 
2016-03-18 11:10:15,728 [4648625]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2016-03-18 11:10:15,728 [4648625]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2016-03-18 11:10:15,728 [4648625]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
2016-03-18 11:10:15,728 [4648625]  ERROR - llij.ide.plugins.PluginManager - Last Action: AceJumpAction 
```

**Comment by jiangyuan** [comment]
has the same issue yet.

**Comment by svenax** [comment]
Me too.

**Comment by marpe** [comment]
+1

**Comment by breandan** [comment]
Please try updating to [AceJump 2.0.9](https://plugins.jetbrains.com/update/index?pr=&updateId=24771) and report any issues encountered. Apologies for the inconvenience. @bimawa

**Comment by bimawa** [comment]
@breandan  thank you fly is normal :+1: 
P.S.Thx for this awesome plugin!
